### ISSUE TITLE
logo size

### ISSUE THREAD

**Issue by jenbrannstrom** [qualifiedleads/mqlblog#3]
Can you make the logo full size, ad remove the circle?
http://prntscr.com/6bp3gt

**Comment by shailesh91** [comment]
What do you mean by full size?

**Comment by jenbrannstrom** [comment]
the image is actually 400px wide or so but the CSS is reducing the size

**Comment by shailesh91** [comment]
Okay, I will try to change it.

**Comment by jenbrannstrom** [comment]
Great!

**Comment by jenbrannstrom** [comment]
Could you reduce the blank space for the logo?
I just noticed it is taking up most of the screen space:

http://prntscr.com/6bpazf

Sorry :(

**Comment by shailesh91** [comment]
I have reduced the size of the logo.
